### ISSUE TITLE
With awesome 3.5 not working

### ISSUE THREAD

**Issue by martku** [travisjeffery/awesome-wm#2]
Hi,
You have done a really nice work. I tried to use the calendar2.lua with awesome 3.5, but it displays some errors.

First I have replaced the "add_signal" with "connect_signal", but it still shows the following error, when click to it:
"calendar2.lua:67: attempt to index field 'widgets' (a nil value)"

Do you have a idea why? How to fix it?

**Comment by Vladimare** [comment]
+1

**Comment by coldfix** [comment]
Hey, in case you're interested: I fixed the calendar widget for awesome 3.5 (and 4.0) and did some (a lot) additional cleanup. It's published as a [separate repository](https://github.com/coldfix/awesome-calendar) but you are of course free to take in any changes you like.

**Comment by Vladimare** [comment]
Tnx, it works

**Comment by martku** [comment]
Nice work @coldfix, thank you.

**Comment by kumarabd** [comment]
So does this error still persist? Is this issue closed?

**Comment by martku** [comment]
Well, it is not fixed here, but it can be closed. Use: https://github.com/coldfix/awesome-calendar
